### ISSUE TITLE
Getting Error The variable 'responseArrayASString' has size of more than '105910233' bytes. 

### ISSUE THREAD

**Issue by yrahulr** [pugliathomas/powerbiscannermetadata#7]
I have followed all the steps mentioned in the video and when I ran the flow it is erroring out at step "Step 3: Retrieve Data"->"Append to String variable" 
The variable 'responseArrayASString' has size of more than '105910233' bytes. This exceeded the maximum size '104857600' allowed.

**Comment by pugliathomas** [comment]
How many datasets do you have in your tenant? Perhaps the flow will need to be configured (create 2) and update the pagination on the workspaces

**Comment by yrahulr** [comment]
More than 6,000 Datasets. Could you please guide me in this?

**Comment by pugliathomas** [comment]
That is quite a bit. 

How many Workspaces are you pulling from? Unfortunately this one flow then would not be able to scale that large, but you could in Step 2 configure it rather than pulling all of the workspaces, stop the batch count after 200. 

In Step 1. it retrieves all of the Workspaces ID (Call modified endpoint) , which then in Step 3 collects each Dataset (Call scanResult endpoint). 
![image](https://user-images.githubusercontent.com/6196804/144690026-280138e9-e926-4ecb-81df-b783a4020d2e.png)


Step 2 then puts each pull into a batch count of 100 workspace ID's. What I would recommend is try a stopper here , (run 0 - 300 workspaces), do step 3, and then go back to step 2 to pull (301 - 500). 
![image](https://user-images.githubusercontent.com/6196804/144690074-854e213f-ad42-49ba-ac6e-a103d3b0e64a.png)

I would recommend reaching out to [ferrybouwman](https://github.com/ferrybouwman) as he originally created the flow here - https://github.com/ferrybouwman/Power-BI-Read-Only-REST-API
